export const ADD_CARD = 'add_card'
export const CREATE_ACCOUNT = 'create_account'
export const MAKE_TRANSFER = 'make_transfer'
export const DEPOSIT_MONEY = 'deposit_money'
export const VIEW_SIGNIN_LOGS = 'view_signin_logs'
export const VIEW_BILLING_HISTORY = 'view_billing_history'
export const CHOOSE_THEME = 'choose_theme'
export const ACCOUNT_SETTINGS = 'account_settings'